### ISSUE TITLE
Support for Hamamatsu CXD/Compix SimplePCI

### ISSUE THREAD

**Issue by gvogler** [tlambert03/napari-bioformats#22]
Hi!

The .cxd file format is implemented as 'Compix SimplePCI' in bioformats ad currently the only way for me to read the data into ImageJ and R. I would love to be able to have this ability for napari as well if possible.

Is this feasible?

Many thanks for all the work!

geo

**Comment by tlambert03** [comment]
hi @gvogler, thanks for the issue.  Can you tell me a bit more?  Are you saying, it works to open .cxd in Fiji via bioformats, but it doesn't work here?  something else?

Side note: this is being gradually deprecated, since I added bioformats support to [aicsimageio](https://github.com/AllenCellModeling/aicsimageio), available in napari via [napari-aicsimageio](https://github.com/AllenCellModeling/napari-aicsimageio) ... 

but, either way, if you tried to open a file and it failed (where it succeeds in bioformats elswhere) can you provide the file?

**Comment by gvogler** [comment]
Sorry, I misunderstood. I tried to import the CXD file with aicsimagio but there it is not supported. I also would want to move away from the Java requirements for bioformats, thus I it would be great if aicsimageio could also read CXD files. But that is not relevant here.

**Comment by tlambert03** [comment]
> I tried to import the CXD file with aicsimagio but there it is not supported. I also would want to move away from the Java requirements for bioformats, thus I it would be great if aicsimageio could also read CXD files. But that is not relevant here.

happy to help with this, since I wrote the bioformats wrapper there as well.

However, you should know that _all_ of these still require java in one way or another (it's quite easy to install via `conda install openjdk` ... and the rest is done for you via these libraries).  Otherwise, it's not "bioformats" anymore.  But reproducing all that work is a Herculean task.


however, if it works in Fiji Bioformats, it _should_ work in aicsimageio, or it's a bug.  You can open an issue there if you'd like, or continue the conversation here.
